services:
  hbase-pseudo:
    image: hbase-pseudo-jsgifbec
    container_name: hbase-pseudo
    hostname: hbase-pseudo
    volumes:
      - /media/SHARED/repositories/BigDataProject/docker/services/hbase-pseudo/data:/data
    ports:
      - 2181:2181
      - 8080:8080
      - 8085:8085
      - 9090:9090
      - 9095:9095
      - 16000:16000 # master
      - 16010:16010 # master-ui
      - 16201-16210:16201-16210 # region servers
      - 16301-16310:16301-16310 # region servers - ui
    restart: unless-stopped
